Add new decode and encode funtions to support 3+ cards copy
Rafalonso/LoRDeckCodesPython pull request #9
Opened 2020-12-06 07:03 UTC by shaobaili3

Thanks for creating this project and being a Lor lover.

I help @wangyi041228 to open a pull request.

She added a few functions to support 3+ cards copy and also sort the faction lists.

2020-12-06 14:23 UTC, Rafalonso requested changes
This changes introduces a lot of code repetition, no tests and ambiguous variable names. Also I'm missing a lot of context for this, why do we need the encode ordering? I have not seen any documentation on this

2020-12-06 14:23 UTC, Rafalonso commented on lor_deckcodes/decode.py
> +    n = data.tell()
Please use more relevant variable names, the code gets very hard to read with single letter names

2020-12-06 14:23 UTC, Rafalonso commented on lor_deckcodes/decode.py
> +        all_cards.extend(_decode_card_block_(data))
This introduces some code repetition with the called function having the same responsibilities as `_decode_card_block`, can you change the algorithm to use it?

2020-12-06 14:23 UTC, Rafalonso commented on lor_deckcodes/encode.py
> +    set_faction_combinations = sorted(set_faction_combinations, key=lambda y: (len([card for card in cards if card.faction == y[1] and card.set == y[0]]), y[0], y[1]))
This should be part of `_get_set_faction_combinations` and I need more context for this

2020-12-06 14:23 UTC, Rafalonso commented on lor_deckcodes/encode.py
> +def _encode_card_block_(data_stream: BytesIO, cards: List["CardCodeAndCount"]) -> None:
Code repetition

2020-12-06 18:07 UTC, wangyi041228 commented
Sorry for my bad codes.

https://github.com/RiotGames/LoRDeckCodes
3.The set/faction lists are ordered by increasing length. The contents of the set/faction lists are ordered alphanumerically.

Source code in C#
https://github.com/RiotGames/LoRDeckCodes/blob/master/LoRDeckCodes/LoRDeckEncoder.cs
line 186

2020-12-06 18:17 UTC, wangyi041228 commented
_encode_card_block for [1, 2, 3] copies and  [4+] copies are kind of different. They have different sorting rule and out style.

2020-12-16 15:31 UTC, Rafalonso approved these changes
Thank you for your contribution, I have cleaned the code a little bit, I'll release this in a bit

2020-12-16 15:31 UTC, merged